# ---------------------------------------- Event Route ----------------------------------------
GET http://localhost:3000/events

###
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
  "name": "Event 1",
  "description": "Event 1 Description",
  "date": "2021-12-31T00:00:00",  
  "price": 100
}

###
@eventId = {{ createEvent.response.body.id }}

###
GET http://localhost:3000/events/{{eventId}}

###
PATCH http://localhost:3000/events/{{eventId}}
Content-Type: application/json

{
  "name": "Event 2 Updated",
  "description": "Event 1 Description Updated",
  "date": "2021-12-31T00:00:00",  
  "price": 200
}

###
DELETE http://localhost:3000/events/{{eventId}}
